/**
 * Clinical and Spanish text sanitizer.
 * Fixes unicode mojibake replacement characters (\uFFFD / ) and restores
 * proper Spanish orthography (accents, inverted question marks, etc.).
 */

const REPLACEMENTS = [
  // Multi-char corruptions & edge cases
  [/papá\uFFFD/g, 'papá'],
  [/miamm\uFFFD/g, 'mi mamá'],
  [/p\uFFFDppa/g, 'papá'],
  [/\uFFFD\?ntima/gi, 'Íntima'],
  [/N\uFFFD/g, 'N°'],
  [/a\uFFFDlo/g, 'año'],
  [/a\uFFFDoq\s*ue/g, 'año que'],
  [/a\uFFFDoq/g, 'año'],
  [/al\uFFFDgoq\s*ue/g, 'algo que'],
  [/al\uFFFDgoq/g, 'algo'],
  [/mas\s+lla\uFFFD/g, 'más allá'],
  [/lla\uFFFD/g, 'allá'],
  [/peuqe\uFFFDo/g, 'pequeño'],
  [/rustraci\uFFFDn/g, 'frustración'],

  // Inverted question marks before specific words
  [/\uFFFDqu\uFFFD/gi, '¿qué'],
  [/\uFFFDQu\uFFFD/g, '¿Qué'],
  [/\uFFFDc\uFFFDmo/gi, '¿cómo'],
  [/\uFFFDd\uFFFDnde/gi, '¿dónde'],
  [/\uFFFDcu\uFFFDl/gi, '¿cuál'],
  [/\uFFFDqui\uFFFDn/gi, '¿quién'],
  [/\uFFFDTe\b/g, '¿Te'],
  [/\uFFFDte\b/g, '¿te'],
  [/\uFFFDAlguna\b/g, '¿Alguna'],
  [/\uFFFDhas\b/g, '¿has'],
  [/\uFFFDHay\b/g, '¿Hay'],
  [/\uFFFDhay\b/g, '¿hay'],
  [/\uFFFDsientes\b/g, '¿sientes'],
  [/\uFFFDSientes\b/g, '¿Sientes'],
  [/\uFFFDcrees\b/g, '¿crees'],
  [/\uFFFDCrees\b/g, '¿Crees'],
  [/\uFFFDy\b/g, '¿y'],
  [/\uFFFDY\b/g, '¿Y'],
  [/\uFFFDEn\b/g, '¿En'],
  [/\uFFFDen\b/g, '¿en'],
  [/\uFFFDqu\b/g, '¿qué'],
  [/\uFFFDQu\b/g, '¿Qué'],
  [/\uFFFDc\b/g, '¿cómo'],
  [/\uFFFDd\b/g, '¿dónde'],
  [/\uFFFDcu\b/g, '¿cuál'],
  [/\uFFFD([A-ZÁÉÍÓÚ])/g, '¿$1'],

  // Specific accented words with \uFFFD
  [/est\uFFFDs/g, 'estás'],
  [/est\uFFFDn/g, 'están'],
  [/est\uFFFD/g, 'está'],
  [/estr\uFFFDs/g, 'estrés'],
  [/Estr\uFFFDs/g, 'Estrés'],
  [/despu\uFFFDs/g, 'después'],
  [/Despu\uFFFDs/g, 'Después'],
  [/F\uFFFDjate/g, 'Fíjate'],
  [/f\uFFFDjate/g, 'fíjate'],
  [/qued\uFFFD/g, 'quedó'],
  [/s\uFFFDper/g, 'súper'],
  [/S\uFFFDper/g, 'Súper'],
  [/m\uFFFDs/g, 'más'],
  [/M\uFFFDs/g, 'Más'],
  [/dif\uFFFDcil/g, 'difícil'],
  [/Dif\uFFFDcil/g, 'Difícil'],
  [/podr\uFFFDas/g, 'podrías'],
  [/podr\uFFFDan/g, 'podrían'],
  [/podr\uFFFDa/g, 'podría'],
  [/dir\uFFFDas/g, 'dirías'],
  [/dem\uFFFDs/g, 'demás'],
  [/catastr\uFFFDficos/g, 'catastróficos'],
  [/prop\uFFFDsito/g, 'propósito'],
  [/Prop\uFFFDsito/g, 'Propósito'],
  [/Ra\uFFFDz/g, 'Raíz'],
  [/ra\uFFFDz/g, 'raíz'],
  [/ra\uFFFDces/g, 'raíces'],
  [/Ra\uFFFDces/g, 'Raíces'],
  [/Hist\uFFFDrica/g, 'Histórica'],
  [/hist\uFFFDrica/g, 'histórica'],
  [/hist\uFFFDrico/g, 'histórico'],
  [/Fisiolog\uFFFDa/g, 'Fisiología'],
  [/fisiolog\uFFFDa/g, 'fisiología'],
  [/fisiol\uFFFDgico/g, 'fisiológico'],
  [/Som\uFFFDtica/g, 'Somática'],
  [/som\uFFFDtica/g, 'somática'],
  [/somatizaci\uFFFDn/g, 'somatización'],
  [/Di\uFFFDlogo/g, 'Diálogo'],
  [/di\uFFFDlogo/g, 'diálogo'],
  [/Autom\uFFFDticos/g, 'Automáticos'],
  [/autom\uFFFDticos/g, 'automáticos'],
  [/autom\uFFFDtica/g, 'automática'],
  [/p\uFFFDrdida/g, 'pérdida'],
  [/P\uFFFDrdida/g, 'Pérdida'],
  [/ser\uFFFDa/g, 'sería'],
  [/pasar\uFFFDa/g, 'pasaría'],
  [/vi\uFFFDndolo/g, 'viéndolo'],
  [/pesad\uFFFDsimo/g, 'pesadísimo'],
  [/f\uFFFDsicamente/g, 'físicamente'],
  [/f\uFFFDsico/g, 'físico'],
  [/f\uFFFDsica/g, 'física'],
  [/a\uFFFDslas/g, 'aíslas'],
  [/imag\uFFFDnate/g, 'imagínate'],
  [/consolar\uFFFDas/g, 'consolarías'],
  [/a\uFFFDos/g, 'años'],
  [/a\uFFFDo/g, 'año'],
  [/r\uFFFDpido/g, 'rápido'],
  [/r\uFFFDpida/g, 'rápida'],
  [/peque\uFFFDito/g, 'pequeñito'],
  [/peque\uFFFDas/g, 'pequeñas'],
  [/peque\uFFFDos/g, 'pequeños'],
  [/peque\uFFFDa/g, 'pequeña'],
  [/peque\uFFFDo/g, 'pequeño'],
  [/ni\uFFFDo/g, 'niño'],
  [/ni\uFFFDos/g, 'niños'],
  [/ni\uFFFDas/g, 'niñas'],
  [/ni\uFFFD/g, 'niño'],
  [/sue\uFFFDo/g, 'sueño'],
  [/sue\uFFFDos/g, 'sueños'],
  [/Sue\uFFFDo/g, 'Sueño'],
  [/d\uFFFDa/g, 'día'],
  [/d\uFFFDas/g, 'días'],
  [/empez\uFFFD/g, 'empezó'],
  [/dej\uFFFD/g, 'dejó'],
  [/detr\uFFFDs/g, 'detrás'],
  [/suceder\uFFFD/g, 'sucederá'],
  [/energ\uFFFDa/g, 'energía'],
  [/pr\uFFFDcticas/g, 'prácticas'],
  [/pr\uFFFDctica/g, 'práctica'],
  [/trav\uFFFDs/g, 'través'],
  [/aut\uFFFDntico/g, 'auténtico'],
  [/aut\uFFFDnticos/g, 'auténticos'],
  [/aut\uFFFDnticas/g, 'auténticas'],
  [/aut\uFFFDntica/g, 'auténtica'],
  [/perpet\uFFFDa/g, 'perpetúa'],
  [/Adem\uFFFDs/g, 'Además'],
  [/adem\uFFFDs/g, 'además'],
  [/as\uFFFD/g, 'así'],
  [/sinti\uFFFDndose/g, 'sintiéndose'],
  [/impidi\uFFFDndole/g, 'impidiéndole'],
  [/autocr\uFFFDtica/g, 'autocrítica'],
  [/cr\uFFFDticos/g, 'críticos'],
  [/cr\uFFFDtico/g, 'crítico'],
  [/experiment\uFFFD/g, 'experimentó'],
  [/a\uFFFDn/g, 'aún'],
  [/m\uFFFDltiples/g, 'múltiples'],
  [/art\uFFFDsticos/g, 'artísticos'],
  [/S\uFFFDntesis/g, 'Síntesis'],
  [/s\uFFFDntesis/g, 'síntesis'],
  [/Qui\uFFFDones/g, 'Quiñones'],
  [/qui\uFFFDones/g, 'quiñones'],
  [/extra\uFFFDo/g, 'extraño'],
  [/extra\uFFFDando/g, 'extrañando'],
  [/ac\uFFFD/g, 'acá'],
  [/all\uFFFD/g, 'allá'],
  [/encontr\uFFFD/g, 'encontró'],
  [/record\uFFFD/g, 'recordó'],
  [/m\uFFFDsica/g, 'música'],
  [/coraz\uFFFDn/g, 'corazón'],
  [/b\uFFFDsqueda/g, 'búsqueda'],
  [/Pizarr\uFFFDn/g, 'Pizarrón'],
  [/pizarr\uFFFDn/g, 'pizarrón'],
  [/\uFFFDngela/g, 'Ángela'],
  [/Sof\uFFFDa/g, 'Sofía'],
  [/Mart\uFFFDnez/g, 'Martínez'],
  [/C\uFFFDdula/g, 'Cédula'],
  [/hab\uFFFDa/g, 'había'],
  [/aqu\uFFFD/g, 'aquí'],
  [/ah\uFFFD/g, 'ahí'],
  [/tambi\uFFFDn/g, 'también'],
  [/patr\uFFFDn/g, 'patrón'],
  [/t\uFFFDcnicas/g, 'técnicas'],
  [/t\uFFFDcnica/g, 'técnica'],
  [/\uFFFDreas/g, 'áreas'],

  // Common -ción / -sión / -xión endings with \uFFFD
  [/([a-zA-ZáéíóúüñÁÉÍÓÚÜÑ]+?)ci\uFFFDn/g, '$1ción'],
  [/([a-zA-ZáéíóúüñÁÉÍÓÚÜÑ]+?)si\uFFFDn/g, '$1sión'],
  [/([a-zA-ZáéíóúüñÁÉÍÓÚÜÑ]+?)xi\uFFFDn/g, '$1xión'],
  [/([a-zA-ZáéíóúüñÁÉÍÓÚÜÑ]+?)ti\uFFFDn/g, '$1tión'],
  [/Ci\uFFFDn/g, 'Ción'],
  [/Si\uFFFDn/g, 'Sión'],
  [/Xi\uFFFDn/g, 'Xión'],

  // Short monosyllabic words with \uFFFD
  [/s\uFFFD\s+que/g, 'sé que'],
  [/(^|[^\wáéíóúüñÁÉÍÓÚÜÑ])s\uFFFD([^\wáéíóúüñÁÉÍÓÚÜÑ]|$)/g, '$1sí$2'],
  [/(^|[^\wáéíóúüñÁÉÍÓÚÜÑ])qu\uFFFD([^\wáéíóúüñÁÉÍÓÚÜÑ]|$)/g, '$1qué$2'],
  [/(^|[^\wáéíóúüñÁÉÍÓÚÜÑ])c\uFFFDmo([^\wáéíóúüñÁÉÍÓÚÜÑ]|$)/g, '$1cómo$2'],
  [/(^|[^\wáéíóúüñÁÉÍÓÚÜÑ])C\uFFFDmo([^\wáéíóúüñÁÉÍÓÚÜÑ]|$)/g, '$1Cómo$2'],
  [/te\s+d\uFFFD([^\wáéíóúüñÁÉÍÓÚÜÑ]|$)/g, 'te dé$1'],
  [/(^|[^\wáéíóúüñÁÉÍÓÚÜÑ])d\uFFFD([^\wáéíóúüñÁÉÍÓÚÜÑ]|$)/g, '$1dé$2'],
  [/(^|[^\wáéíóúüñÁÉÍÓÚÜÑ])\uFFFDl([^\wáéíóúüñÁÉÍÓÚÜÑ]|$)/g, '$1él$2'],

  // Defensive: Also fix words if \uFFFD was completely dropped
  [/\bEstrs\b/g, 'Estrés'],
  [/\bestrs\b/g, 'estrés'],
  [/\bProcrastinacin\b/g, 'Procrastinación'],
  [/\bprocrastinacin\b/g, 'procrastinación'],
  [/\bSensacin\b/g, 'Sensación'],
  [/\bsensacin\b/g, 'sensación'],
  [/\bReaccin\b/g, 'Reacción'],
  [/\breaccin\b/g, 'reacción'],
  [/\bpropsito\b/g, 'propósito'],
  [/\bPropsito\b/g, 'Propósito'],
  [/\bpodras\b/g, 'podrías'],
  [/\bpodran\b/g, 'podrían'],
  [/\bFisiologa\b/g, 'Fisiología'],
  [/\bfisiologa\b/g, 'fisiología'],
  [/\bSomtica\b/g, 'Somática'],
  [/\bsomtica\b/g, 'somática'],
  [/\bRaz\b/g, 'Raíz'],
  [/\braz\b/g, 'raíz'],
  [/\bHistrica\b/g, 'Histórica'],
  [/\bhistrica\b/g, 'histórica'],
  [/\bAutomticos\b/g, 'Automáticos'],
  [/\bautomticos\b/g, 'automáticos'],
  [/\bIntegracin\b/g, 'Integración'],
  [/\bintegracin\b/g, 'integración'],
  [/\bDilogo\b/g, 'Diálogo'],
  [/\bdilogo\b/g, 'diálogo'],
  [/\bprdida\b/g, 'pérdida'],
  [/\bPrdida\b/g, 'Pérdida'],
  [/\btensin\b/g, 'tensión'],
  [/\bTensin\b/g, 'Tensión'],
  [/\bdespus\b/g, 'después'],
  [/\bDespus\b/g, 'Después'],
  [/\bSper\b/g, 'Súper'],
  [/\bsper\b/g, 'súper'],
  [/\bdifcil\b/g, 'difícil'],
  [/\bDifcil\b/g, 'Difícil'],
  [/\bFjate\b/g, 'Fíjate'],
  [/\bfjate\b/g, 'fíjate'],
  [/\bqued\b/g, 'quedó'],
  [/\b([a-zA-ZáéíóúüñÁÉÍÓÚÜÑ]+?)cin\b/g, '$1ción'],
  [/\b([a-zA-ZáéíóúüñÁÉÍÓÚÜÑ]+?)sin\b/g, '$1sión'],
  [/\b([a-zA-ZáéíóúüñÁÉÍÓÚÜÑ]+?)xin\b/g, '$1xión'],
  [/^Qu\b/g, '¿Qué'],
  [/\bQu actividades\b/g, '¿Qué actividades'],
  [/\bCmo\b/g, '¿Cómo']
];

export function sanitizeSpanishText(str) {
  if (typeof str !== 'string' || !str) return str;
  let res = str;
  for (let i = 0; i < REPLACEMENTS.length; i++) {
    res = res.replace(REPLACEMENTS[i][0], REPLACEMENTS[i][1]);
  }
  return res;
}

export function sanitizeNodeObject(node) {
  if (!node || typeof node !== 'object') return node;
  return {
    ...node,
    label: sanitizeSpanishText(node.label),
    description: sanitizeSpanishText(node.description),
    reflection_question: sanitizeSpanishText(node.reflection_question),
    observations: sanitizeSpanishText(node.observations),
    challenge: sanitizeSpanishText(node.challenge),
    source: sanitizeSpanishText(node.source),
    question: sanitizeSpanishText(node.question),
    questions: Array.isArray(node.questions) ? node.questions.map(sanitizeSpanishText) : node.questions,
    perspectives_metadata: Array.isArray(node.perspectives_metadata)
      ? node.perspectives_metadata.map(p => ({
          ...p,
          name: sanitizeSpanishText(p.name),
          question: sanitizeSpanishText(p.question)
        }))
      : node.perspectives_metadata
  };
}

export function sanitizeAfcGraph(graph) {
  if (!graph || typeof graph !== 'object') return graph;
  return {
    ...graph,
    nodes: Array.isArray(graph.nodes) ? graph.nodes.map(sanitizeNodeObject) : graph.nodes
  };
}
