/**
 * Clinical and Spanish text sanitizer.
 * Fixes unicode mojibake replacement characters ([\uFFFD]+ / ) and restores
 * proper Spanish orthography (accents, inverted question marks, etc.).
 */

const REPLACEMENTS = [
  // Multi-char corruptions & edge cases
  [/papá\uFFFD+/g, 'papá'],
  [/miamm\uFFFD+/g, 'mi mamá'],
  [/p\uFFFD+ppa/g, 'papá'],
  [/\uFFFD+\?ntima/gi, 'Íntima'],
  [/N\uFFFD+/g, 'N°'],
  [/a\uFFFD+lo/g, 'año'],
  [/a\uFFFD+oq\s*ue/g, 'año que'],
  [/a\uFFFD+oq/g, 'año'],
  [/al\uFFFD+goq\s*ue/g, 'algo que'],
  [/al\uFFFD+goq/g, 'algo'],
  [/mas\s+lla\uFFFD+/g, 'más allá'],
  [/lla\uFFFD+/g, 'allá'],
  [/peuqe\uFFFD+o/g, 'pequeño'],
  [/rustraci\uFFFD+n/g, 'frustración'],
  [/\bt[\uFFFD]+\s+est/gi, 'tú est'],
  [/\bT[\uFFFD]+\s+est/g, 'Tú est'],
  [/tambi[\uFFFD]+n/gi, 'también'],
  [/Tambi[\uFFFD]+n/g, 'También'],
  [/regulaci[\uFFFD]+n/gi, 'regulación'],
  [/atenci[\uFFFD]+n/gi, 'atención'],
  [/funcionar[\uFFFD]+/gi, 'funcionará'],
  [/est[\uFFFD]+ndares/gi, 'estándares'],
  [/\ba m[\uFFFD]+\s+mism/gi, 'a mí mism'],
  [/energ[\uFFFD]+a/gi, 'energía'],
  [/relaci[\uFFFD]+n/gi, 'relación'],
  [/sensaci[\uFFFD]+n/gi, 'sensación'],
  [/evitaci[\uFFFD]+n/gi, 'evitación'],
  [/dif[\uFFFD]+cil/gi, 'difícil'],
  [/cl[\uFFFD]+nic/gi, 'clínic'],
  [/ma[\uFFFD]+an/gi, 'mañan'],
  [/est[\uFFFD]+tic/gi, 'estétic'],
  [/p[\uFFFD]+rdida/gi, 'pérdida'],
  [/P[\uFFFD]+rdida/gi, 'Pérdida'],
  [/[\uFFFD]+nica\b/gi, 'única'],
  [/[\uFFFD]+nico\b/gi, 'único'],
  [/[\uFFFD]+Alquimia/g, 'Alquimia'],
  [/¿Qu[\uFFFD]+/gi, '¿Qué'],
  [/¿qu[\uFFFD]+/gi, '¿qué'],
  [/¿c[\uFFFD]+mo/gi, '¿cómo'],
  [/¿d[\uFFFD]+nde/gi, '¿dónde'],

  // Inverted question marks before specific words
  [/[\uFFFD]+qu[\uFFFD]+/gi, '¿qué'],
  [/[\uFFFD]+Qu[\uFFFD]+/g, '¿Qué'],
  [/[\uFFFD]+c[\uFFFD]+mo/gi, '¿cómo'],
  [/[\uFFFD]+d[\uFFFD]+nde/gi, '¿dónde'],
  [/[\uFFFD]+cu[\uFFFD]+l/gi, '¿cuál'],
  [/[\uFFFD]+qui[\uFFFD]+n/gi, '¿quién'],
  [/[\uFFFD]+Te\b/g, '¿Te'],
  [/[\uFFFD]+te\b/g, '¿te'],
  [/[\uFFFD]+Alguna\b/g, '¿Alguna'],
  [/[\uFFFD]+has\b/g, '¿has'],
  [/[\uFFFD]+Hay\b/g, '¿Hay'],
  [/[\uFFFD]+hay\b/g, '¿hay'],
  [/[\uFFFD]+sientes\b/g, '¿sientes'],
  [/[\uFFFD]+Sientes\b/g, '¿Sientes'],
  [/[\uFFFD]+crees\b/g, '¿crees'],
  [/[\uFFFD]+Crees\b/g, '¿Crees'],
  [/[\uFFFD]+y\b/g, '¿y'],
  [/[\uFFFD]+Y\b/g, '¿Y'],
  [/[\uFFFD]+En\b/g, '¿En'],
  [/[\uFFFD]+en\b/g, '¿en'],
  [/[\uFFFD]+qu\b/g, '¿qué'],
  [/[\uFFFD]+Qu\b/g, '¿Qué'],
  [/[\uFFFD]+c\b/g, '¿cómo'],
  [/[\uFFFD]+d\b/g, '¿dónde'],
  [/[\uFFFD]+cu\b/g, '¿cuál'],
  [/[\uFFFD]+([A-ZÁÉÍÓÚ])/g, '¿$1'],

    [/ju[\uFFFD]+gale/gi, 'juégale'],
  // Specific accented words with [\uFFFD]+
  [/est[\uFFFD]+s/g, 'estás'],
  [/est[\uFFFD]+n/g, 'están'],
  [/est[\uFFFD]+/g, 'está'],
  [/estr[\uFFFD]+s/g, 'estrés'],
  [/Estr[\uFFFD]+s/g, 'Estrés'],
  [/despu[\uFFFD]+s/g, 'después'],
  [/Despu[\uFFFD]+s/g, 'Después'],
  [/F[\uFFFD]+jate/g, 'Fíjate'],
  [/f[\uFFFD]+jate/g, 'fíjate'],
  [/qued[\uFFFD]+/g, 'quedó'],
  [/s[\uFFFD]+per/g, 'súper'],
  [/S[\uFFFD]+per/g, 'Súper'],
  [/m[\uFFFD]+s/g, 'más'],
  [/M[\uFFFD]+s/g, 'Más'],
  [/dif[\uFFFD]+cil/g, 'difícil'],
  [/Dif[\uFFFD]+cil/g, 'Difícil'],
  [/podr[\uFFFD]+as/g, 'podrías'],
  [/podr[\uFFFD]+an/g, 'podrían'],
  [/podr[\uFFFD]+a/g, 'podría'],
  [/dir[\uFFFD]+as/g, 'dirías'],
  [/dem[\uFFFD]+s/g, 'demás'],
  [/catastr[\uFFFD]+ficos/g, 'catastróficos'],
  [/prop[\uFFFD]+sito/g, 'propósito'],
  [/Prop[\uFFFD]+sito/g, 'Propósito'],
  [/Ra[\uFFFD]+z/g, 'Raíz'],
  [/ra[\uFFFD]+z/g, 'raíz'],
  [/ra[\uFFFD]+ces/g, 'raíces'],
  [/Ra[\uFFFD]+ces/g, 'Raíces'],
  [/Hist[\uFFFD]+rica/g, 'Histórica'],
  [/hist[\uFFFD]+rica/g, 'histórica'],
  [/hist[\uFFFD]+rico/g, 'histórico'],
  [/Fisiolog[\uFFFD]+a/g, 'Fisiología'],
  [/fisiolog[\uFFFD]+a/g, 'fisiología'],
  [/fisiol[\uFFFD]+gico/g, 'fisiológico'],
  [/Som[\uFFFD]+tica/g, 'Somática'],
  [/som[\uFFFD]+tica/g, 'somática'],
  [/somatizaci[\uFFFD]+n/g, 'somatización'],
  [/Di[\uFFFD]+logo/g, 'Diálogo'],
  [/di[\uFFFD]+logo/g, 'diálogo'],
  [/Autom[\uFFFD]+ticos/g, 'Automáticos'],
  [/autom[\uFFFD]+ticos/g, 'automáticos'],
  [/autom[\uFFFD]+tica/g, 'automática'],
  [/p[\uFFFD]+rdida/g, 'pérdida'],
  [/P[\uFFFD]+rdida/g, 'Pérdida'],
  [/ser[\uFFFD]+a/g, 'sería'],
  [/pasar[\uFFFD]+a/g, 'pasaría'],
  [/vi[\uFFFD]+ndolo/g, 'viéndolo'],
  [/pesad[\uFFFD]+simo/g, 'pesadísimo'],
  [/f[\uFFFD]+sicamente/g, 'físicamente'],
  [/f[\uFFFD]+sico/g, 'físico'],
  [/f[\uFFFD]+sica/g, 'física'],
  [/a[\uFFFD]+slas/g, 'aíslas'],
  [/imag[\uFFFD]+nate/g, 'imagínate'],
  [/consolar[\uFFFD]+as/g, 'consolarías'],
  [/a[\uFFFD]+os/g, 'años'],
  [/a[\uFFFD]+o/g, 'año'],
  [/r[\uFFFD]+pido/g, 'rápido'],
  [/r[\uFFFD]+pida/g, 'rápida'],
  [/peque[\uFFFD]+ito/g, 'pequeñito'],
  [/peque[\uFFFD]+as/g, 'pequeñas'],
  [/peque[\uFFFD]+os/g, 'pequeños'],
  [/peque[\uFFFD]+a/g, 'pequeña'],
  [/peque[\uFFFD]+o/g, 'pequeño'],
  [/ni[\uFFFD]+o/g, 'niño'],
  [/ni[\uFFFD]+os/g, 'niños'],
  [/ni[\uFFFD]+as/g, 'niñas'],
  [/ni[\uFFFD]+/g, 'niño'],
  [/sue[\uFFFD]+o/g, 'sueño'],
  [/sue[\uFFFD]+os/g, 'sueños'],
  [/Sue[\uFFFD]+o/g, 'Sueño'],
  [/d[\uFFFD]+a/g, 'día'],
  [/d[\uFFFD]+as/g, 'días'],
  [/empez[\uFFFD]+/g, 'empezó'],
  [/dej[\uFFFD]+/g, 'dejó'],
  [/detr[\uFFFD]+s/g, 'detrás'],
  [/suceder[\uFFFD]+/g, 'sucederá'],
  [/energ[\uFFFD]+a/g, 'energía'],
  [/pr[\uFFFD]+cticas/g, 'prácticas'],
  [/pr[\uFFFD]+ctica/g, 'práctica'],
  [/trav[\uFFFD]+s/g, 'través'],
  [/aut[\uFFFD]+ntico/g, 'auténtico'],
  [/aut[\uFFFD]+nticos/g, 'auténticos'],
  [/aut[\uFFFD]+nticas/g, 'auténticas'],
  [/aut[\uFFFD]+ntica/g, 'auténtica'],
  [/perpet[\uFFFD]+a/g, 'perpetúa'],
  [/Adem[\uFFFD]+s/g, 'Además'],
  [/adem[\uFFFD]+s/g, 'además'],
  [/as[\uFFFD]+/g, 'así'],
  [/sinti[\uFFFD]+ndose/g, 'sintiéndose'],
  [/impidi[\uFFFD]+ndole/g, 'impidiéndole'],
  [/autocr[\uFFFD]+tica/g, 'autocrítica'],
  [/cr[\uFFFD]+ticos/g, 'críticos'],
  [/cr[\uFFFD]+tico/g, 'crítico'],
  [/experiment[\uFFFD]+/g, 'experimentó'],
  [/a[\uFFFD]+n/g, 'aún'],
  [/m[\uFFFD]+ltiples/g, 'múltiples'],
  [/art[\uFFFD]+sticos/g, 'artísticos'],
  [/S[\uFFFD]+ntesis/g, 'Síntesis'],
  [/s[\uFFFD]+ntesis/g, 'síntesis'],
  [/Qui[\uFFFD]+ones/g, 'Quiñones'],
  [/qui[\uFFFD]+ones/g, 'quiñones'],
  [/extra[\uFFFD]+o/g, 'extraño'],
  [/extra[\uFFFD]+ando/g, 'extrañando'],
  [/ac[\uFFFD]+/g, 'acá'],
  [/all[\uFFFD]+/g, 'allá'],
  [/encontr[\uFFFD]+/g, 'encontró'],
  [/record[\uFFFD]+/g, 'recordó'],
  [/m[\uFFFD]+sica/g, 'música'],
  [/coraz[\uFFFD]+n/g, 'corazón'],
  [/b[\uFFFD]+squeda/g, 'búsqueda'],
  [/Pizarr[\uFFFD]+n/g, 'Pizarrón'],
  [/pizarr[\uFFFD]+n/g, 'pizarrón'],
  [/[\uFFFD]+ngela/g, 'Ángela'],
  [/Sof[\uFFFD]+a/g, 'Sofía'],
  [/Mart[\uFFFD]+nez/g, 'Martínez'],
  [/C[\uFFFD]+dula/g, 'Cédula'],
  [/hab[\uFFFD]+a/g, 'había'],
  [/aqu[\uFFFD]+/g, 'aquí'],
  [/ah[\uFFFD]+/g, 'ahí'],
  [/tambi[\uFFFD]+n/g, 'también'],
  [/patr[\uFFFD]+n/g, 'patrón'],
  [/t[\uFFFD]+cnicas/g, 'técnicas'],
  [/t[\uFFFD]+cnica/g, 'técnica'],
  [/[\uFFFD]+reas/g, 'áreas'],

  // Common -ción / -sión / -xión endings with [\uFFFD]+
  [/([a-zA-ZáéíóúüñÁÉÍÓÚÜÑ]+?)ci[\uFFFD]+n/g, '$1ción'],
  [/([a-zA-ZáéíóúüñÁÉÍÓÚÜÑ]+?)si[\uFFFD]+n/g, '$1sión'],
  [/([a-zA-ZáéíóúüñÁÉÍÓÚÜÑ]+?)xi[\uFFFD]+n/g, '$1xión'],
  [/([a-zA-ZáéíóúüñÁÉÍÓÚÜÑ]+?)ti[\uFFFD]+n/g, '$1tión'],
  [/Ci[\uFFFD]+n/g, 'Ción'],
  [/Si[\uFFFD]+n/g, 'Sión'],
  [/Xi[\uFFFD]+n/g, 'Xión'],

  // Short monosyllabic words with [\uFFFD]+
  [/s[\uFFFD]+\s+que/g, 'sé que'],
  [/(^|[^\wáéíóúüñÁÉÍÓÚÜÑ])s[\uFFFD]+([^\wáéíóúüñÁÉÍÓÚÜÑ]|$)/g, '$1sí$2'],
  [/(^|[^\wáéíóúüñÁÉÍÓÚÜÑ])qu[\uFFFD]+([^\wáéíóúüñÁÉÍÓÚÜÑ]|$)/g, '$1qué$2'],
  [/(^|[^\wáéíóúüñÁÉÍÓÚÜÑ])c[\uFFFD]+mo([^\wáéíóúüñÁÉÍÓÚÜÑ]|$)/g, '$1cómo$2'],
  [/(^|[^\wáéíóúüñÁÉÍÓÚÜÑ])C[\uFFFD]+mo([^\wáéíóúüñÁÉÍÓÚÜÑ]|$)/g, '$1Cómo$2'],
  [/te\s+d[\uFFFD]+([^\wáéíóúüñÁÉÍÓÚÜÑ]|$)/g, 'te dé$1'],
  [/(^|[^\wáéíóúüñÁÉÍÓÚÜÑ])d[\uFFFD]+([^\wáéíóúüñÁÉÍÓÚÜÑ]|$)/g, '$1dé$2'],
  [/(^|[^\wáéíóúüñÁÉÍÓÚÜÑ])[\uFFFD]+l([^\wáéíóúüñÁÉÍÓÚÜÑ]|$)/g, '$1él$2'],

  // Defensive: Also fix words if [\uFFFD]+ was completely dropped
  [/\bEstrs\b/g, 'Estrés'],
  [/\bestrs\b/g, 'estrés'],
  [/\bProcrastinacin\b/g, 'Procrastinación'],
  [/\bprocrastinacin\b/g, 'procrastinación'],
  [/\bSensacin\b/g, 'Sensación'],
  [/\bsensacin\b/g, 'sensación'],
  [/\bReaccin\b/g, 'Reacción'],
  [/\breaccin\b/g, 'reacción'],
  [/\bpropsito\b/g, 'propósito'],
  [/\bPropsito\b/g, 'Propósito'],
  [/\bpodras\b/g, 'podrías'],
  [/\bpodran\b/g, 'podrían'],
  [/\bFisiologa\b/g, 'Fisiología'],
  [/\bfisiologa\b/g, 'fisiología'],
  [/\bSomtica\b/g, 'Somática'],
  [/\bsomtica\b/g, 'somática'],
  [/\bRaz\b/g, 'Raíz'],
  [/\braz\b/g, 'raíz'],
  [/\bHistrica\b/g, 'Histórica'],
  [/\bhistrica\b/g, 'histórica'],
  [/\bAutomticos\b/g, 'Automáticos'],
  [/\bautomticos\b/g, 'automáticos'],
  [/\bIntegracin\b/g, 'Integración'],
  [/\bintegracin\b/g, 'integración'],
  [/\bDilogo\b/g, 'Diálogo'],
  [/\bdilogo\b/g, 'diálogo'],
  [/\bprdida\b/g, 'pérdida'],
  [/\bPrdida\b/g, 'Pérdida'],
  [/\btensin\b/g, 'tensión'],
  [/\bTensin\b/g, 'Tensión'],
  [/\bdespus\b/g, 'después'],
  [/\bDespus\b/g, 'Después'],
  [/\bSper\b/g, 'Súper'],
  [/\bsper\b/g, 'súper'],
  [/\bdifcil\b/g, 'difícil'],
  [/\bDifcil\b/g, 'Difícil'],
  [/\bFjate\b/g, 'Fíjate'],
  [/\bfjate\b/g, 'fíjate'],
  [/\bqued\b/g, 'quedó'],
  [/\b([a-zA-ZáéíóúüñÁÉÍÓÚÜÑ]+?)cin\b/g, '$1ción'],
  [/\b([a-zA-ZáéíóúüñÁÉÍÓÚÜÑ]+?)sin\b/g, '$1sión'],
  [/\b([a-zA-ZáéíóúüñÁÉÍÓÚÜÑ]+?)xin\b/g, '$1xión'],
  [/^Qu\b/g, '¿Qué'],
  [/\bQu actividades\b/g, '¿Qué actividades'],
  [/\bCmo\b/g, '¿Cómo'],
  [/[\uFFFD]{2,}/g, ' • '],
  [/[\uFFFD]/g, '']
];

export function sanitizeSpanishText(str) {
  if (typeof str !== 'string' || !str) return str;
  let res = str;
  for (let i = 0; i < REPLACEMENTS.length; i++) {
    res = res.replace(REPLACEMENTS[i][0], REPLACEMENTS[i][1]);
  }
  return res;
}

export function sanitizeNodeObject(node) {
  if (!node || typeof node !== 'object') return node;
  return {
    ...node,
    label: sanitizeSpanishText(node.label),
    description: sanitizeSpanishText(node.description),
    reflection_question: sanitizeSpanishText(node.reflection_question),
    observations: sanitizeSpanishText(node.observations),
    challenge: sanitizeSpanishText(node.challenge),
    source: sanitizeSpanishText(node.source),
    question: sanitizeSpanishText(node.question),
    questions: Array.isArray(node.questions) ? node.questions.map(sanitizeSpanishText) : node.questions,
    perspectives_metadata: Array.isArray(node.perspectives_metadata)
      ? node.perspectives_metadata.map(p => ({
          ...p,
          name: sanitizeSpanishText(p.name),
          question: sanitizeSpanishText(p.question)
        }))
      : node.perspectives_metadata
  };
}

export function sanitizeAfcGraph(graph) {
  if (!graph || typeof graph !== 'object') return graph;
  return {
    ...graph,
    nodes: Array.isArray(graph.nodes) ? graph.nodes.map(sanitizeNodeObject) : graph.nodes
  };
}
